version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=verysecretpassword
      - POSTGRES_USER=jddiehl17
      - POSTGRES_DB=Novata
    ports:
      - "5432:5432"
